services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.12.3
    container_name: clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./etc/clickhouse-server:/etc/clickhouse-server
      - ./logs:/var/log/clickhouse-server
      - ./data:/var/lib/clickhouse
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE